### ISSUE TITLE
Glyph #1510 is named _t

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#10]
I was looking at how to access all the ligatures and noticed that 
glyph #1510 (EADA) is named `_t` (in `JuniusX-Regular.ttf`).
So I opened `Junicode-width.glyphs` in FontLab and took a look.
There the glyph is named `uniF127_t` .
So to test I exported just the normal width regular weight.
In that test file (`Junicode-width.ttf`) it became glyph #1511 and is named `glyph1511` .

So I am guessing that Glyphs may have an issue with `uniF127` in the glyph name.
It appears FontLab did not like it either.
Or ? ? ?

**Comment by psb1558** [comment]
First, I discovered while investigating this that the shape of  U+F127 was wrong, so I've corrected that.

Glyphs is renaming uniF127_t --> uniF127_uni0074 on export, as you can see by running ttx on the ttf file. It appears that FontLab is renaming glyphs on import, and with that one it is throwing up its hands, presumably because it doesn't know what to do with the codepoint in the PUA. I've changed the production name to uniF1270074: try that, but I doubt it will help. The FontLab renaming algorithm doesn't appear to have anticipated a case like this. Which isn't surprising, since this is a seriously weird glyph--the only ligature in MUFI where the first element is PUA-encoded.

Perhaps the name should be longs_t.alt, though I wouldn't be surprised if FontLab tries to rename that too.

In any case, I've done these things:
- Made uniF127 a variant of s, accessible via cv21:4. This makes it searchable as an s in a PDF.
- Added a rule "sub uniF127 t by uniF127_t" in liga "Standard Ligatures."

**Comment by kenmcd** [comment]
Thanks.
Looks good in FontCreator now that I turned-off the name change option.
Also turned-off a similar option in FontLab, looks fine now; did not test the export.
Tested font with `cv21=4` applied in LibreOffice - works fine.

**Comment by psb1558** [comment]
Further thoughts/changes. This kind of problem arises occasionally because of MUFI's habit of encoding everything in the PUA. When things get sticky, I sometimes introduce an unencoded duplicate. In this case we have:
- uniF127, the MUFI alternate longs, used only if user keys it in directly.
- longs.alt2 (unencoded), selected with cv21=4.
- uniEADA, used only if user keys it in (but why would they do that?)
- longs_t.alt (unencoded), a ligature of either **uniF127 t** or **longs.alt2 t**, selected via liga.
These unencoded glyphs should behave properly in a search, and the names shouldn't cause a problem for FontLab.

I guess this is fixed now.
