### ISSUE TITLE
WinDescent & WinAscent cutting-off characters

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#19]
While working on the documentation in LibreOffice I noticed the bottom of the dot of the alternate dotted yogh (yoghflatdot)  was being cut-off.
So I checked further and the dot on the lowercase dotted g (E501) was also cut-off.
This is for the Regular weight.
So I also checked the Bold weight.
As expected the same characters are also cut-off by WinDescent.
But also in the Bold the top of many characters were also cut-off.
Obviously Aringacute, but also 1E64, 1E2E, 01D9, 01D7, and more.

This issue comes-up over and over in the LibreOffice "forum" and bug tracker.
For LibreOffice on Windows users there is no solution but to fix the fonts.

I am now also seeing this issue coming-up in the Affinity Publisher on Windows forum.
Same situation, the font has to be changed or it is simply broken to Windows users.

Knowledgeable users will set the line-height/leading directly so if the fonts WinAscent/WinDescent settings accommodate all the characters there is no issue with excessive line height.
But if the metrics do not fit all characters, Windows users are just out of luck.

So I request that the WinAscent/WinDescent vertical metrics settings accommodate all characters.
With a little extra space because the hinting will still cut it off onscreen at smaller sizes.

**Comment by psb1558** [comment]
I've been very focused on the outlines and to some extent the horizontal metrics, but not at all on the vertical metrics. I generally leave this for late in the process, since I want to have the same set of numbers in the roman and italic faces (and the italic is probably at least a year away from the state the roman is in). It's also part of this process to work on the tallest glyphs, shaving off as much height as possible, and that is part of the fine-tuning of the font.

This is to say, I guess, that while I have put in some (I hope) workable numbers for the vertical metrics, these come with a warning that they are likely very different from what will be in the final production font.

**Comment by kenmcd** [comment]
Checked the Bold font and all of it looks OK now with one exception.
The uni1EB2 (Latin capital letter A with breve and hook above) - the hook is just over the WinAscent enough that it will get a bit of a flat top in LibreOffice on Windows
.

**Comment by psb1558** [comment]
In the Bold master, the top of the glyph is at the WinAscent (2100), but in the generated font it's 2107. So something is going wrong in the interpolation. I'll figure it out.

**Comment by psb1558** [comment]
It's behaving now. Will upload later tonight.

Check out the file Changes_post_MUFI_4.0, because there's a new combining mark and new ligatures.

**Comment by kenmcd** [comment]
Looks good.
