### ISSUE TITLE
Proposed changes to Stylistic Sets (for comment)

### ISSUE THREAD

**Issue by psb1558** [psb1558/Junicode-New#28]
1. Change the behavior of ss01 so that English þð --> Nordic when the language is English and Nordic þð --> English when the language is anything other than English. (In other words, ss01 would reverse the effect of locl.)

2. Delete ss03 (Long s). It duplicates hist and is only here for the benefit of MS Word users, who don't have access to hist. But the font does not otherwise cater to MS Word users.

3. Change the tag ss10 to ornm ("Ornaments"), which is what it ought to be. Once again MS Word users disadvantaged, but this font can't cater to them.

4. Delete ss20, whose function is taken over by ss01.

The effect of these changes would be to free up three ss features: 03, 10 and 20.

**Comment by kenmcd** [comment]
1, 3, and 4 all make sense to me. All for it.

Regarding # 2 - ss03 Long s - the `calt` processing for English and French affects this.
What would be the base _Long s_ feature if not `ss03`?
Just trying to wrap my head around how this would now work compared to before.
Recently spent some time dissecting and documenting the _Long s_ `calt` effects on this and on _r rotunda_ `ss11` and am having trouble visualizing it at the moment.
If `hist` replaces `ss03` should that also happen for `ss11`?
That would be easier to explain rather than in two different places.
Right now `ss03` and `ss11` work sort of the same which makes it easier to understand.

**Comment by psb1558** [comment]
Thanks for the comment, @kenmcd. I see your point about hist. Oddly, Junicode has for a long time had only s --> longs in hist, and has duplicated hist as ss03.

hist is a difficult feature for a font like this one to handle. For a script font like Eadui, which belongs to a well-defined place and time, it's easy to decide what hist should do--but what should JuniusX do, when it covers periods from the Roman empire to the 18th century? If you put all the historical stuff into hist you get a jumble. So I ended up putting only longs in hist and duplicating that as ss03 for the benefit of MS Word users.

Lately I've been running out of patience with MS Word--thus the idea of getting rid of ss03. (But perhaps people are used to having it around ...)

**Comment by psb1558** [comment]
I have done 1, 3 and 4.

Ornm now follows the OpenType recommendation by supplying the ornaments in two ways: one as indexed variants (0-28) of the bullet character (U+2022), and the other as variants of the letters a-z and A-C.
