### ISSUE TITLE
Missing ligatures in old Junicode bold font

### ISSUE THREAD

**Issue by hadisfr** [psb1558/Junicode-New#31]
Hi!

I was wondering why some ligatures (e.g. `st`-> `ﬆ ` `U+FB06`) are available in regular and italic subfamilies of Junicode but are missing from bold subfamily.

It seems that this is fixed in JuniusX .

**P.S.** Considering this state, do you recommend using the current version of JuniusX for publishing a book, or you consider it unstable yet and I should use the old Junicode? The book is not written in English (It's primarily in Arabic script.) and only has got some English words in each page and an English title page.

**Comment by psb1558** [comment]
Many characters are missing in Junicode's bold faces, simplyl because I never got around to filling them up. JuniusX is an update of Junicode intended to address that and other problems. I've adopted tools and a workflow that makes it easier to manage a large project.

I think JuniusX roman is stable enough for production use, especially in a project like the one you describe. JuniusX italic is far from ready, but if you can mix JuniusX roman and Junicode italic you should be fine.

**Comment by hadisfr** [comment]
So I'll try mixing both. Thank you. :D
