### ISSUE TITLE
Suggestion: expanded option

### ISSUE THREAD

**Issue by manuelmagan** [psb1558/Junicode-New#50]
Hello. In Medieval Studies we work a lot with stretched letters that are difficult to work with. An expanded width would do the job easily. It'd be much appreciated.
Thank you so much and thank you very much for your work.

**Comment by psb1558** [comment]
A year or two ago I experimented with SemiExpanded and Expanded widths, thus:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/16215767/111292729-decc3d80-861e-11eb-8612-80a7b42c7919.png">
What stalled the project was quality control. It's easy to make the Glyphs program generate an expanded face, but the procedure tends to magnify any tiny flaw in an outline, so that the result requires a good bit of tweaking by hand. With 1,965 unique outlines in the font, the commitment of time is significant, and right now I have to spend what time I've got bringing the italic up to speed.

As with so much else in this nearly thirty-year-old project, the answer is "Sure . . . one of these days."

**Comment by manuelmagan** [comment]
I understand. 
Thanks again for the project!

**Comment by psb1558** [comment]
I've decided to go ahead and add Expanded and SemiExpanded widths. They are in the source for the roman face (but not yet italic), but the necessary refinements of the outlines has only been done (so far) for the ranges a-z, A-Z, and basic punctuation. **Many of the other glyphs will look bad!** I have not added Expanded and SemiExpanded fonts, but these will eventually include versions of all five weights—that is, ten new fonts.

The new widths are available in the Variable Font, JuniusVF.ttf, and the STAT table has been revised to take account of them.

**Comment by psb1558** [comment]
Samples:
<img width="144" alt="image" src="https://user-images.githubusercontent.com/16215767/114236707-ffeb2a00-994f-11eb-907e-4db73f77d1b7.png">
<img width="156" alt="image" src="https://user-images.githubusercontent.com/16215767/114236736-07aace80-9950-11eb-9a53-b5a1abf7b907.png">

**Comment by manuelmagan** [comment]
Thank you so much! They look really good.

**Comment by psb1558** [comment]
The collection of static fonts (i.e. standard TrueType) in the fonts directory now includes Expanded and SemiExpanded widths in all weights. Here are all widths in the Regular weight:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/16215767/115993617-9a2ead00-a5a1-11eb-9aee-1af6c39c3403.png">
The basic Latin alphabet has been edited so that it looks good in the new widths, but be warned that many glyphs have not yet been edited, and they can look very bad. For example, here is the phonetic "ram's horn" character in the Expanded Light face:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/16215767/115993709-05787f00-a5a2-11eb-90d3-d99aeb2155d8.png">
It will take quite a bit of time to adjust every outline in the font, but a side effect of doing it will be that all the widths and weights will look better in the end. In the meantime, use the Expanded and SemiExpanded fonts with caution.

**Comment by manuelmagan** [comment]
Thanks again. Great work!
